# GitLab CI/CD configuration file for NEXTGEN UI repository
include:
  - template: Jobs/Container-Scanning.gitlab-ci.yml

stages:
  - build
  - unit_test
  - sonarqube
  - test
  - deploy

image: registry.sh.nextgenwaterprediction.com/infrastructure/docker/docker:latest

variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE
    DOCKER_IMAGE_TAG: $CI_COMMIT_REF_NAME

build:
  stage: build
  script:
    - echo "Logging in to Gitlab Container Registry..."
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "Building ${CI_PROJECT_NAME} docker image.. "
    - docker compose build
    - docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - echo "Building ${CI_PROJECT_NAME} Production docker image.. "
    - docker compose -f production-pw.yaml build
    - docker tag $DOCKER_IMAGE_NAME:latest $DOCKER_IMAGE_NAME:prod
    - docker logout

unit-test:
  stage: unit_test
  image: $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
  script:
    # TODO add unit tests when available
    - echo "Running Unit Tests..."

sonarqube:
  stage: sonarqube
  image:
    name: registry.sh.nextgenwaterprediction.com/infrastructure/sonar-scanner-cli/sonar-scanner-cli:5.0.1
    entrypoint: [""]
  variables:
    # Defines the location of the analysis task cache
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    # Shallow cloning needs to be disabled.
    # See https://docs.sonarqube.org/latest/analysis/gitlab-cicd/.
    GIT_DEPTH: 0
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner -X -Dsonar.verbose=true

container_scanning:
  stage: test
  needs:
    - build
  variables:
    SECURE_LOG_LEVEL: info
    CS_SEVERITY_THRESHOLD: UNKNOWN
    CS_IMAGE: $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

container_scanning_prod:
  extends: container_scanning
  stage: test
  needs:
    - build
  variables:
    SECURE_LOG_LEVEL: info
    CS_SEVERITY_THRESHOLD: UNKNOWN
    CS_IMAGE: $DOCKER_IMAGE_NAME:prod

deploy:
  stage: deploy
  script:
    - echo "Logging in to Gitlab Container Registry to push the image..."
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo "Pushing to the docker registry"
    - docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKER_IMAGE_NAME:latest
    - docker push $DOCKER_IMAGE_NAME:latest
    - docker push $DOCKER_IMAGE_NAME:prod
    - docker logout
  rules:
    - if: '$CI_COMMIT_BRANCH == "development"'
